version: '3.1'

services:
  postgresql:
    build: postgresql
    environment:
      - POSTGRES_PASSWORD=teste123
      - POSTGRES_USER=teste
      - POSTGRES_DB=teste
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  dns_faker:
    build: dns_faker

  site:
    build: site
    ports:
      - 8000:8000

